#!/bin/sh

set -e

USAGE="$0 <version>"

VERSION="$(echo $1 | grep --only-matching -E '[0-9]+\.[0-9]+\.[0-9]')"

if [ -z "$VERSION" ]; then
  echo $USAGE
  exit 1
fi

if ! which -s eggs; then
  echo "==> Installing eggs"
  deno install -A -f --unstable -n eggs https://x.nest.land/eggs@0.2.1/mod.ts
fi

echo "==> Publishing version $VERSION"
eggs link "$EGGS_API_TOKEN"
eggs publish --version "$VERSION"
